<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Đặt hàng Form Submission',
	'heading' => 'New Form Submission',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Checked',
		'checkbox_unchecked' => 'Unchecked',
		'submitted_from' => 'Form submitted from website: %s',
		'submitted_by' => 'Visitor IP address: %s',
		'too_many_submissions' => 'Too many recent submissions from this IP',
		'failed_to_send_email' => 'Failed to send email',
		'invalid_reCAPTCHA_private_key' => 'Invalid reCAPTCHA private key.',
		'invalid_reCAPTCHA2_private_key' => 'Invalid reCAPTCHA 2.0 private key.',
		'invalid_reCAPTCHA2_server_response' => 'Invalid reCAPTCHA 2.0 server response.',
		'invalid_field_type' => 'Unknown field type \'%s\'.',
		'invalid_form_config' => 'Field \'%s\' has an invalid configuration.',
		'unknown_method' => 'Unknown server request method'
	),
	'email' => array(
		'from' => 'rosehipdan@gmail.com',
		'to' => 'rosehipdan@gmail.com'
	),
	'fields' => array(
		'custom_U10116' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Họ và Tên',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Họ và Tên\' is required.'
			)
		),
		'Email' => array(
			'order' => 2,
			'type' => 'email',
			'label' => 'Tên đăng nhập',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Tên đăng nhập\' is required.',
				'format' => 'Field \'Tên đăng nhập\' has an invalid email.'
			)
		),
		'custom_U10160' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Số điện thoại',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Số điện thoại\' is required.'
			)
		),
		'custom_U10268' => array(
			'order' => 4,
			'type' => 'string',
			'label' => 'Mật khẩu',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Mật khẩu\' is required.'
			)
		),
		'custom_U10283' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Nhập lại mật khẩu',
			'required' => true,
			'errors' => array(
				'required' => 'Field \'Nhập lại mật khẩu\' is required.'
			)
		)
	)
);

process_form($form);
?>
